### PR TITLE
Create delete-lab-user-accounts-instead-of-disabling-them.md

### PR DESCRIPTION
**Pull request by vicoler**
An improvement to the lab cleanup process by implementing the deletion of user accounts instead of merely disabling or suspending them.

### CODE REVIEW

**Comment by vicoler** [comment]
06/08/2023 prod release. this is ready to be published.

**Comment by vicoler** [comment]
This is ready to be published today

**Comment by vicoler** [comment]
This is ready to be published today.

**Comment by dillonreese** [comment]
Discussed with Victor. Document should not read like an announcement.

**Pull request merged**
